version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2400252815
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: my_django_app
    depends_on:
      - db
      - redis
    command: ["./wait-for.sh", "db:5432", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2400252815
      POSTGRES_DB: mydatabase
      REDIS_URL: redis://my_redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
