# Generated by Django 5.1.1 on 2025-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_event_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(to='ticket.attendee'),
        ),
    ]
